import Head from 'next/head'
import Intro from '../compnents/HomepageComponents/Intro'
import Services from '../compnents/HomepageComponents/Services'
import {data} from '../data'
export default function Home({services}) {
  console.log(services)
  return (
    <>
    <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
       <Intro />
       <Services />
    </>
    
  )
}



export const getStaticProps = async ()=>{
  const services = data
  return ({
    props:{ 
      services
    }
  })
}